### PR TITLE
FEC-9012 - We dont read mediaType VOD configuration

### PR DESCRIPTION
**Pull request by RoyBregman**
When we get in the configuration that mediatype is vod and the asset is live we return that the player is in live state - the actual result here should be that the player will load in VOD mode and not in Live mode (UI)

The change was to add a check that isLive in the player will return false if explicitly set as type VOD

### CODE REVIEW

**Comment by OrenMe** [comment]
@RoyBregman please pay attention to conventions. The title of the PR can’t be merged like this!
@yairans FYI

**Comment by OrenMe** [comment]
Needs to be

> fix(FEC-9012): add mediaType VOD configuration check fonisLive verification

Reference for standard-version: https://github.com/conventional-changelog/standard-version#commit-message-convention-at-a-glance

**Comment by RoyBregman** [comment]
fix(FEC-9012): add mediaType VOD configuration check for isLive verification

**Comment by OrenMe** [comment]
@RoyBregman please delete the branch once merged(use the delete branch button in the PR)

**Pull request merged**
