### PR TITLE
fix(FEC-8709): cannot seek to the end in paused mode

### PR DESCRIPTION
**Pull request by yairans**
### Description of the Changes
**issue:** Caused by https://github.com/kaltura/playkit-js/pull/135 
**Solution:** enable seeking to the end in paused mode

### CheckLists

- [x] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment 
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

### CODE REVIEW

**Comment by yairans** [comment]
Problematic fix. now seeking to the end in IE does not trigger `ended` (no replay button). 
Maybe need to add login to fire `ended` manually when `currentTime >= duration`.

**Comment by kaltura-hooks** [comment]
Hi @yairans,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by OrenMe** [comment]
@yairans what is the status? can we close this?

**Comment by yairans** [comment]
Yes. it's known limitation.

**Pull request closed without merging**
